name: Run Prettier Formatter

on:
  push:
    branches:
      - "**" # Run on pushes to all branches
  pull_request:
    branches:
      - "**" # Run on all pull requests

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format
